# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='genome',
        ),
        migrations.AddField(
            model_name='genome',
            name='genome',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
    ]
