# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160415_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='sequence',
            field=models.TextField(editable=False),
        ),
    ]
