# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160415_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='sequence',
            field=models.TextField(),
        ),
    ]
